name: CTest
on:
  push:
  pull_request:
jobs:
  reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure without ALP/GraphBLAS
        run: cmake -S cpp/alp-graphblas -B build -DALP_GRAPHBLAS_ENABLE=OFF
      - name: Build
        run: cmake --build build -j
      - name: Test
        run: ctest --test-dir build --output-on-failure
